services:
  - type: web
    name: domex-kids-strapi
    runtime: node
    repo: https://github.com/aniflax/Domex-Kids
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
